apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/insights-results-smart-proxy?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/docker-build.yaml
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: smart-proxy
    appstudio.openshift.io/component: smart-proxy
    pipelines.appstudio.openshift.io/type: build
  name: smart-proxy-on-push
  namespace: obsint-processing-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/obsint-processing-tenant/smart-proxy/smart-proxy:{{revision}}
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: .
  pipelineRef:
    name: docker-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-smart-proxy
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
