name: Go tests

on:
  push:
    branches: ["master", "main"]
  pull_request:

permissions:
  contents: read

jobs:
  gotests:
    uses: RedHatInsights/processing-tools/.github/workflows/gotests.yaml@master
    with:
      coverage_threshold: 50
    secrets: inherit
